export { default as Inicio } from "./Inicio";
export { default as Operaciones } from "./Operaciones";
export { default as OperacionCancelada } from "./OperacionCancelada";
export { default as Exito } from "./Exito";
export { default as Saldo } from "./Saldo";
export { default as Extraccion } from "./Extraccion";
export { default as Deposito } from "./Deposito";
export { default as OtroMonto } from "./OtroMonto";
export { default as Error } from "./Error";
